services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=supakeny
      - POSTGRES_PASSWORD=Password_123
    ports:
      - 5432:5432
    volumes:
      - './postgres_data:/var/lib/postgresql/data'